# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    - ./Scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
